# ============================================================
# embedding.py
# ------------------------------------------------------------
# Responsibility:
#   Convert text into an embedding vector using
#   Azure OpenAI text-embedding-3-small.
#
# Security:
#   Azure credentials are loaded from .env.
#   The API key is never hardcoded in this file.
# ============================================================

import os

from dotenv import load_dotenv
from openai import OpenAI


# ------------------------------------------------------------
# 1. Load environment variables from .env
# ------------------------------------------------------------

load_dotenv()


# ------------------------------------------------------------
# 2. Read Azure OpenAI configuration
# ------------------------------------------------------------

AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
AZURE_OPENAI_EMBEDDING_DEPLOYMENT = os.getenv(
    "AZURE_OPENAI_EMBEDDING_DEPLOYMENT"
)


# ------------------------------------------------------------
# 3. Create Azure OpenAI client
# ------------------------------------------------------------

client = OpenAI(
    api_key=AZURE_OPENAI_API_KEY,
    base_url=f"{AZURE_OPENAI_ENDPOINT.rstrip('/')}/openai/v1/",
)


# ------------------------------------------------------------
# 4. Create embedding
# ------------------------------------------------------------

def create_embedding(text: str) -> list[float]:
    """
    Convert the supplied text into an embedding vector.

    Parameters:
        text (str):
            Text that needs to be converted into a vector.

    Returns:
        list[float]:
            Numeric embedding vector generated by Azure OpenAI.
    """

    response = client.embeddings.create(
        model=AZURE_OPENAI_EMBEDDING_DEPLOYMENT,
        input=text,
    )

    return response.data[0].embedding


# ------------------------------------------------------------
# 5. Test the embedding function
# ------------------------------------------------------------

if __name__ == "__main__":

    test_text = "This is my first RAG chatbot embedding test."

    embedding = create_embedding(test_text)

    print("Embedding generated successfully.")
    print("Embedding dimensions:", len(embedding))
    print("First 5 values:", embedding[:5])